[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "starlette>=0.47.0",
    "tensorflow>=2.19.0",
    "tf-keras>=2.19.0",
    "torch>=2.7.0",
    "transformers>=4.52.4",
    "uvicorn>=0.34.3",
]
